### ISSUE TITLE
Feature Request - option to change gradient area

### ISSUE THREAD

**Issue by rekenaar00** [dropqube/pv-forecast-card#6]
Hi, thanks for the great card.

Currently, it seems that the gradient on the colored area is always a 50/50 split on the available value. So even on a day with a low forecast, you will get half of the low value as green.

Would it be possible to apply the split on the maximum value instead? Then on a low forecast day, it will not even show green.

![Image](https://github.com/user-attachments/assets/16c3ced1-df84-4e9f-a380-d771eb04f48c)

Not sure if I make sense, I dont want the whole area to be colored, I still want the gradient only applied to the available part, but only yellow if available is below 50 for example.

**Comment by rekenaar00** [comment]
so this is what I'm talking about, Friday is les than half, so I don't want any green in it

![Image](https://github.com/user-attachments/assets/85a3c315-f3c2-4ff0-aeb3-501650c95ff0)

**Comment by BenRutlandWeb** [comment]
This is something I also wanted. If you're using [card mod](https://github.com/thomasloven/lovelace-card-mod) you can add this to the config:

```yaml
bar_color_start: var(--yellow-color)
bar_color_end: var(--green-color)
card_mod:
  style: |
    ha-card .bar-container {
      container-type: inline-size;
    }
    ha-card .bar {
      background-size: 100cqi;
    }
```

<img width="466" height="232" alt="Image" src="https://github.com/user-attachments/assets/2637c688-573b-46c3-a173-75ca0d3aaa70" />


If you want more solid looking colors, you can do some background-size trickery:

```yaml
bar_color_start: |
  var(--red-color), 
  var(--deep-orange-color), 
  var(--orange-color), 
  var(--amber-color)
bar_color_end: |
  var(--yellow-color), 
  var(--lime-color), 
  var(--light-green-color), 
  var(--green-color)
card_mod:
  style: |
    ha-card .bar-container {
      container-type: inline-size;
    }
    ha-card .bar {
      background-size: 800cqi; /* 100cqi × the number of color stops */
      background-position-x: var(--bar-width);
    }
```

<img width="466" height="232" alt="Image" src="https://github.com/user-attachments/assets/e2c98d6e-00f1-47ea-b2ba-9e3d452d9a4d" />
